apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-backend
  template:
    metadata:
      labels:
        app: app-backend
    spec:
      containers:
      - name: app-backend
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: app-backend-service
spec:
  selector:
    app: app-backend  
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 8090
  type: ClusterIP