apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-frontend
  template:
    metadata:
      labels:
        app: app-frontend
    spec:
      containers:
      - name: app-frontend
        image: IMAGE_PLACEHOLDER
        env:
          - name: BACKEND_URL
            value: http://app-backend-service:80
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-frontend-service
spec:
  selector:
    app: app-frontend  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080  
  type: NodePort